Работа с библиотекой NumPy

1. Импорт библиотеки NumPy с общепринятым сокращением

In [1]:
import numpy as np

print("NumPy успешно импортирован, версия:", np.__version__)

NumPy успешно импортирован, версия: 2.3.5


2. Примеры создания массивов

In [2]:
# из обычного Python-списка
list_array = np.array([1, 2, 3, 4, 5])
print("Массив из списка:", list_array)

# из списка списков двумерный массив
matrix_from_list = np.array([[1, 2, 3],
                             [4, 5, 6]])
print("\n2D-массив из списка списков:\n", matrix_from_list)

# с помощью встроенных функций
zeros_arr = np.zeros((3, 4))
ones_arr  = np.ones((2, 5))
arange_arr = np.arange(0, 20, 2)
linspace_arr = np.linspace(0, 1, 11)

print("\nМассив нулей 3×4:\n", zeros_arr)
print("\nМассив единиц 2×5:\n", ones_arr)
print("\nnp.arange(0, 20, 2):", arange_arr)
print("np.linspace(0, 1, 11):", linspace_arr)

Массив из списка: [1 2 3 4 5]

2D-массив из списка списков:
 [[1 2 3]
 [4 5 6]]

Массив нулей 3×4:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Массив единиц 2×5:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

np.arange(0, 20, 2): [ 0  2  4  6  8 10 12 14 16 18]
np.linspace(0, 1, 11): [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


3. Демонстрация атрибутов

In [3]:
print("Форма массива matrix_from_list:", matrix_from_list.shape)
print("Тип данных элементов:", matrix_from_list.dtype)

# Пример с другим типом данных
float_array = np.array([[1.5, 2.7], [3.2, 4.8]])
print("\nМассив с вещественными числами:\n", float_array)
print("shape:", float_array.shape, "dtype:", float_array.dtype)


Форма массива matrix_from_list: (2, 3)
Тип данных элементов: int64

Массив с вещественными числами:
 [[1.5 2.7]
 [3.2 4.8]]
shape: (2, 2) dtype: float64


4. Пример индексирования и срезов

In [4]:
print("Одномерный массив:", arange_arr)
print("Первый элемент:", arange_arr[0])
print("Последний элемент:", arange_arr[-1])
print("Срез с 2-го по 5-й элемент (не включая 5-й):", arange_arr[2:5])

# Двумерный массив
print("\nДвумерный массив:\n", matrix_from_list)
print("Элемент на позиции [0, 1]:", matrix_from_list[0, 1])
print("Первая строка:", matrix_from_list[0])
print("Второй столбец:", matrix_from_list[:, 1])
print("Подмассив 2×2 из левого верхнего угла:\n", matrix_from_list[:2, :2])

Одномерный массив: [ 0  2  4  6  8 10 12 14 16 18]
Первый элемент: 0
Последний элемент: 18
Срез с 2-го по 5-й элемент (не включая 5-й): [4 6 8]

Двумерный массив:
 [[1 2 3]
 [4 5 6]]
Элемент на позиции [0, 1]: 2
Первая строка: [1 2 3]
Второй столбец: [2 5]
Подмассив 2×2 из левого верхнего угла:
 [[1 2]
 [4 5]]


5. Примеры Векторных операций и базовых статистик

In [5]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

# Поэлементные операции (векторизация)
print("a + b  =", a + b)
print("a * b  =", a * b)
print("a ** 2 =", a ** 2)
print("2 + a * 3 =", 2 + a * 3)

# Базовые статистические функции
data = np.array([7, 2, 9, 1, 5, 8, 3])

print("\nИсходные данные:", data)
print("Среднее (mean):      ", data.mean())
print("Медиана:             ", np.median(data))
print("Сумма:               ", data.sum())
print("Минимум:             ", data.min())
print("Максимум:            ", data.max())
print("Стандартное отклонение:", data.std())

# Пример статистик по осям для 2D-массива
print("\nСреднее по строкам матрицы:\n", matrix_from_list.mean(axis=1))
print("Среднее по столбцам матрицы:", matrix_from_list.mean(axis=0))

a + b  = [11 22 33 44]
a * b  = [ 10  40  90 160]
a ** 2 = [ 1  4  9 16]
2 + a * 3 = [ 5  8 11 14]

Исходные данные: [7 2 9 1 5 8 3]
Среднее (mean):       5.0
Медиана:              5.0
Сумма:                35
Минимум:              1
Максимум:             9
Стандартное отклонение: 2.878491668515698

Среднее по строкам матрицы:
 [2. 5.]
Среднее по столбцам матрицы: [2.5 3.5 4.5]
